- censys/certificates.py
- censys/ipv4.py
- censys/websites.py
I fixed a major bug introduced by me. This bug leads to multiple requests to the same page while using the new generators.
I'm very sorry for that!
> fix a major (!) bug in generators

- censys/data.py
Adds the CensysData class for interacting with /data endpoints.
> Add support for the Censys data API

- README.md
- censys/base.py
- censys/certificates.py
- censys/data.py
- censys/ipv4.py
- fixes tests in `base.py`, `certificates.py`, `data.py`, `ipv4.py`
```bash
python setup.py test
```
Some aspects of the API have changed, and some tests looked for things that have changed. So the tests we're updated
> Update failing tests

- README.md
Signed-off-by: Aidan Holland <aidan@censys.io>
> Update link to RTD

- censys/asm/__init__.py
- censys/asm/client.py
- censys/asm/clouds.py
- censys/asm/events.py
- censys/v2/api.py
- tests/asm/test_clouds.py
- tests/utils.py
Closes #64 
```python
from datetime import date
from censys import AsmClient
c = AsmClient("API_KEY")
count = c.clouds.get_host_counts(date(2021, 1, 1))
print(count)
```
```bash
$ pytest tests/asm/test_clouds.py
```
> [ASM] Added /v1/clouds/hostCounts/

- censys/asm/assets/domains.py
- tests/asm/test_assets.py
> [ASM] Domain Assets: Get Subdomains

- censys/asm/clouds.py
- censys/common/exceptions.py
- tests/asm/test_clouds.py
> Add Cloud Count Endpoints

- README.md
- censys/asm/seeds.py
- censys/cli/args.py
- censys/cli/commands/__init__.py
- censys/cli/commands/asm.py
- censys/cli/commands/config.py
- censys/cli/commands/hnri.py
- censys/cli/commands/search.py
- censys/cli/commands/view.py
- censys/cli/utils.py
- censys/common/base.py
- docs/index.rst
- docs/quick-start.rst
- docs/usage-cli.rst
- pyproject.toml
- tests/asm/test_assets.py
- tests/asm/test_events.py
- tests/asm/test_seeds.py
- tests/cli/test_asm.py
- tests/cli/test_cli.py
- tests/cli/test_view.py
- tests/test_base.py
- tests/utils.py
- Separated ASM CLI
- Added new `add-seeds` command
- Added support for cookies
- Refactored CLI
> feat(CLI): Adds ASM Subcommands (add-seeds)

- censys/cli/utils.py
- censys/search/v1/api.py
- censys/search/v2/api.py
- poetry.lock
- pyproject.toml
- tests/search/v2/test_api.py
- tests/search/v2/test_hosts.py
- Updated deps
- Aliased `account()` for v2 clients
- Added infinite page option with `pages = -1`
- Deprecated CSV output
Closes #146
> Misc v1 to v2 Changes

- .flake8
- censys/asm/__init__.py
- censys/asm/api.py
- censys/asm/assets/assets.py
- censys/asm/assets/certificates.py
- censys/asm/assets/domains.py
- censys/asm/assets/hosts.py
- censys/asm/client.py
- censys/asm/risks.py
- censys/cli/commands/asm.py
- censys/cli/commands/config.py
- censys/cli/commands/hnri.py
- censys/cli/commands/search.py
- censys/cli/commands/view.py
- censys/cli/utils.py
- censys/common/base.py
- censys/common/config.py
- censys/common/deprecation.py
- censys/common/exceptions.py
- censys/search/client.py
- censys/search/v1/api.py
- censys/search/v2/api.py
- poetry.lock
- pyproject.toml
- tests/asm/test_api.py
- tests/asm/test_assets.py
- tests/asm/test_risks.py
- tests/cli/test_hnri.py
- tests/cli/test_search.py
- tests/cli/test_view.py
- Added `darglint` dev dependency
- Updated docstrings
- Added delete comment endpoint
- Added `Risks` API
Closes #138
> feat: Add ASM Risks Endpoints

- .github/workflows/python-ci.yml
- censys/common/base.py
- censys/search/v2/api.py
- censys/search/v2/certs.py
- censys/search/v2/hosts.py
- docs/usage-v1.rst
- docs/usage-v2.rst
- pyproject.toml
- tests/search/v2/test_comments.py
- tests/search/v2/test_tags.py
- tests/test_base.py
> feat(api): Add Tagging and Comments

- censys/cli/commands/__init__.py
- censys/cli/commands/account.py
- censys/cli/utils.py
- censys/common/base.py
- tests/cli/test_account.py
- tests/cli/test_cli.py
- tests/cli/test_view.py
- Added `censys account` command
Closes #164
> feat(cli): New Account Command

- .github/workflows/python-ci.yml
- censys/common/base.py
> feat(ci): Test on Python 3.6

- censys/search/v2/api.py
- docs/usage-v2.rst
- tests/search/v2/test_comments.py
Testing
```python
from censys.search import CensysHosts
h = CensysHosts()
h.update_comment("1.1.1.1", 101, "This is an updated test comment")
h.delete_comment("1.1.1.1", 101)
```
> feat(api): Update and Delete Comment Support

- .github/CODE_OF_CONDUCT.md
- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/question.md
- .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
- .github/workflows/stale.yml
- censys/cli/commands/search.py
- censys/search/v2/api.py
- censys/search/v2/hosts.py
- examples/search/search_hosts.py
- poetry.lock
- pyproject.toml
- tests/cli/test_search.py
- tests/search/v2/test_hosts.py
- Added `**kwargs` for the `search` method.
- Added `virtual_hosts` to the host `search` method.
- Added `--virtual-hosts` to the search cli.
- Updated `mypy` and `flake8`.
- Formatted various markdown.
Closes #217
> feat(api): Search Virtual Hosts

- .flake8
- censys/search/v2/certs.py
- docs/usage-v2.rst
- examples/search/report_certs.py
- examples/search/search_certs.py
- examples/search/view_cert.py
- Removed private methods from autodocs.
- Reworded docs to clarify separation of v1 and v2 certificate indexes.
> chore(docs): Update Certificate V2 Language

- .flake8
- docs/usage-v2.rst
- examples/README.md
- examples/search/aggregate_hosts.py
- examples/search/metadata_hosts.py
- examples/search/search_client.py
- examples/search/search_hosts.py
- examples/search/view_host.py
- examples/search/view_host_diff.py
- examples/search/view_host_events.py
- examples/search/view_host_names.py
- Used the `include` RST directive to import example files
- Added example JSONs
> chore(docs): Update docs to include new APIs

- censys/search/v2/api.py
- censys/search/v2/hosts.py
- tests/search/v2/test_hosts.py
- Added the `virtual_hosts` argument to `aggregate` function.
> chore(api): Add virtual_hosts to the aggregate function

- README.md
- examples/search/aggregate_hosts.py
- poetry.lock
- pyproject.toml
- Ran `poetry update`
- Updated examples
> Bump Versions and Update

- censys/asm/api.py
- censys/asm/assets/assets.py
- censys/asm/assets/subdomains.py
- censys/asm/clouds.py
- censys/asm/events.py
- censys/asm/risks.py
- censys/asm/risks/__init__.py
- censys/asm/risks/v1.py
- censys/asm/risks/v2.py
- censys/asm/seeds.py
- censys/cli/commands/search.py
- censys/common/base.py
- censys/common/exceptions.py
- censys/search/__init__.py
- censys/search/v2/api.py
- poetry.lock
- pyproject.toml
- tests/asm/test_assets.py
- tests/asm/test_clouds.py
- tests/asm/test_events.py
- tests/asm/test_risks.py
- tests/asm/test_seeds.py
- tests/asm/utils.py
- tests/cli/test_asm.py
- tests/cli/test_search.py
- tests/search/v2/test_hosts.py
- Added support for the v2 Risks API
- Updated ASM Exceptions
- Added support for virtual hosts in the `view_all` method
- Added a `raw_search` method to increase usability
> feat(api): Add v2 Risks API

- .github/CONTRIBUTING.md
- README.md
- censys/asm/client.py
- censys/common/base.py
- examples/README.md
- examples/asm/add_seeds_bulk.py
- tests/asm/utils.py
- Updated `AsmClient` to include both Risks APIs
- Added example for `Add Seeds in Bulk (from CSV)`
- Updated `CONTRIBUTING.md`
- Added commit message convention
> chore: Misc cleanup

- tests/asm/test_risks.py
Update language to match changes in `discover` and `pipeline` repos
> fix:update language to match pipeline/discover

- censys/__main__.py
This allows python -m censys to  execute the CLI, which is otherwise often not on $PATH.
> Add __main__.py

- censys/asm/__init__.py
- censys/cli/commands/subdomains.py
- docs/cli.html
- docs/cli.rst
- docs/conf.py
- docs/requirements.txt
- docs/usage-cli.rst
- Embeded Asciinema cast
- Exported both Risks v1 and v2
- Pinned `sphinx-tabs` version
- Added Google Analytics
> docs: Misc fixes and updates

- censys/asm/__init__.py
- censys/asm/client.py
- censys/asm/inventory.py
- censys/asm/risks/__init__.py
- docs/usage-asm.rst
- tests/asm/test_inventory.py
- Added ASM Inventory Search API
Closes #368
> feat(asm-api): Add Inventory Search

- .flake8
- censys/asm/__init__.py
- censys/asm/assets/__init__.py
- censys/asm/assets/assets.py
- censys/asm/assets/object_storage.py
- censys/asm/beta.py
- censys/asm/client.py
- censys/asm/clouds.py
- censys/asm/logbook.py
- censys/common/utils.py
- docs/usage-asm.rst
- examples/asm/get_host_risks.py
- tests/asm/test_assets.py
- tests/asm/test_beta.py
- tests/asm/test_clouds.py
- tests/asm/test_events.py
- tests/asm/utils.py
- tests/test_utils.py
Added all Beta ASM API Endpoints as well as miscellaneous updates. 
- Added `Beta` ASM API class
- Updated the `Events` class to be called `Logbook`
- Added the Object Storage Asset type
- Updated and tested various time parsing utils
> Add Beta Endpoints

- censys/search/v2/api.py
- censys/search/v2/hosts.py
- examples/search/search_hosts.py
- tests/search/v2/test_hosts.py
- Updated the search fields logic
> chore(api): update the method to specify search fields

- .github/workflows/pypi.yml
- .github/workflows/python-ci.yml
- README.md
- pyproject.toml
> Bump Version to 2.2.4

- censys/asm/seeds.py
- censys/cli/commands/search.py
- censys/cli/data/hosts_autocomplete.json
- tests/cli/test_search.py
- Added support for host fields in the CLI
- Updated host autocomplete
- Fixed seeds types
> Update CLI and Autocomplete

- .github/workflows/python-ci.yml
- .readthedocs.yml
- README.md
- censys/cli/commands/search.py
- censys/cli/data/hosts_autocomplete.json
- docs/Makefile
- docs/conf.py
- docs/requirements.txt
- poetry.lock
- pyproject.toml
- tests/cli/test_search.py
- Added `--timeout` option for the search command
- Updated various packages
- Updated hosts autocomplete
> Add Timeout for Search CLI

- README.md
- censys/asm/__init__.py
- censys/asm/client.py
- censys/asm/saved_queries.py
- censys/cli/commands/account.py
- censys/cli/commands/asm.py
- censys/cli/commands/hnri.py
- censys/cli/commands/search.py
- censys/cli/commands/subdomains.py
- censys/cli/commands/view.py
- censys/cli/utils.py
- censys/common/base.py
- censys/search/__init__.py
- docs/usage-asm.rst
- docs/usage-cli.rst
- examples/asm/add_saved_queries.py
- examples/asm/delete_saved_query_by_id.py
- examples/asm/edit_saved_query_by_id.py
- examples/asm/get_saved_queries.py
- examples/asm/get_saved_query_by_id.py
- pyproject.toml
- tests/asm/test_saved_queries.py
- tests/asm/utils.py
- tests/cli/test_asm.py
- tests/cli/test_search.py
- tests/cli/test_subdomains.py
- tests/search/v2/test_hosts.py
Add support to the CLI and API for the ASM saved query APIs.
> feat: Add CLI and API support for ASM saved queries
